### ISSUE TITLE
Cannot join the Google Group - https://groups.google.com/forum/#!forum/3d-morphable-models

### ISSUE THREAD

**Issue by facesvision** [3d-morphable-models/curated-list-of-awesome-3D-Morphable-Model-software-and-data#9]
The readme mentions the following [link](https://groups.google.com/forum/#!forum/3d-morphable-models) for the google group for related discussions and resources. But I see a message saying 'Content Unavailable'. Is this still active? If not, are there similar channels around this? I would really like to get involved with the likeminded community and work in this field.

**Comment by BernhardEgger** [comment]
if you send me an email I can add you to the list
egger.bernhard@gmail.com

Best
Bernhard

**Comment by BernhardEgger** [comment]
The setting of the group is however set in a way that you should be able to sign up - you might need to be logged in :)
